language: python
python:
- 2.7
- 3.6
- "nightly"
matrix:
  allow_failures:
    - python: "nightly"

sudo: false

install:
  - pip install -r requirements.txt
  - pip install -r requirements_dev.txt
  - export MPLBACKEND="agg"

script:
  - travis_wait 30 nosetests tests -v -s
